In [1]:
import numpy as np

In [2]:
path = "/home/andrea/Desktop/Baseline6Prime/Write_S3_MW2_W8/"
files = [[],[],[]]
for vm in range(1, 4):
    for instance in range(1, 3):
        for rep in range(1, 4):
            files[rep-1].append(path+"VM"+str(vm)+"_"+str(instance)+"/rep"+str(rep)+"/output.log")
            

In [3]:
latency = np.zeros(4)
throughput = np.zeros(4)
for rep in range(1, 4):
     
    for j in range(0, len(files[rep-1])):
        fileI = open(files[rep-1][j], "r")
        linesI = []
        for line in fileI:
            linesI.append(line)

        xI = np.asarray(linesI)
        

        countI = 0
        i = 2
        while xI[i] != "ALL STATS\n":
            countI += 1
            i += 1

        i += 4  #4 per set, 5 per get, 7 per 50%50
        z = xI[i][6:]
        m = 0
        numbers = 0
        singleLatency = ""
        singleThroughput = ""
        while numbers < 3:
            while z[m] == " ":
                m += 1
            while z[m] != " ":
                if numbers == 0:
                    singleThroughput += z[m]
                m += 1 
            numbers += 1
        while z[m] == " ":
                m += 1
        while z[m] != " ":
            singleLatency += z[m]
            m += 1

        latency[rep-1] += float(singleLatency)
        throughput[rep-1] += float(singleThroughput)
        
    latency[rep-1] = latency[rep-1] / 6

throughput[3] = np.mean(throughput[0:3])
print((throughput[0:3] - throughput[3])**2)
latency[3] = np.mean(latency[0:3])

FileNotFoundError: [Errno 2] No such file or directory: '/home/andrea/Desktop/Baseline6Prime/Write_S3_MW2_W8/VM1_1/rep1/output.log'

In [106]:
fileOutput = open(path+"results.txt", "w")

In [107]:
fileOutput.write("Servers: 3\tMiddleware: 2\tWorker Threads: 8\n")
fileOutput.write("Throuhgput: ")
fileOutput.write(str(throughput[0])+ " " + str(throughput[1]) + " " + str(throughput[2]))
fileOutput.write("\nAverage Throughput: ")
fileOutput.write(str(throughput[3]))
fileOutput.write('\nResponse Time: ')
fileOutput.write(str(latency[0])+ " " + str(latency[1]) + " " + str(latency[2]))
fileOutput.write("\nAverage Response Time: ")
fileOutput.write(str(latency[3]))

fileOutput.close()

In [1]:
import numpy as np

In [2]:
totError = 0
S = 0
M = 0
W = 0
SM = 0
SW = 0
MW = 0
SMW = 0
I = 0
type = "50Set50Get"
for server in [2, 3]:
    for mw in [1,2]:
        for workers in [8, 32]:
            if server == 2:
                Svalue = -1
            else:
                Svalue = 1
            if mw == 1:
                Mvalue = -1
            else:
                Mvalue = 1
            if workers == 8:
                Wvalue = -1
            else:
                Wvalue = 1
            
            fileI = open("/home/andrea/Desktop/Final/Baseline6Prime/"+type+"_S"+str(server)+"_MW"+str(mw)+"_W"+str(workers)+"/results.txt", "r")
            linesI = []
            for line in fileI:
                linesI.append(line)

            xI = np.asarray(linesI)

            throughput = np.zeros(4)
            throughput[0] = float(xI[1].split(" ")[1])
            throughput[1] = float(xI[1].split(" ")[2])
            throughput[2] = float(xI[1].split(" ")[3])

            meanThroughput = float(xI[2].split(" ")[2])
            I += meanThroughput
            S += Svalue*meanThroughput
            M += Mvalue*meanThroughput
            W += Wvalue*meanThroughput
            SM += Svalue*Mvalue*meanThroughput
            SW += Svalue*Wvalue*meanThroughput
            MW += Mvalue*Wvalue*meanThroughput
            SMW += Svalue*Mvalue*Wvalue*meanThroughput

            print(xI[0])
            print(xI[1])
            print(xI[2])
            totError += (throughput[0] - meanThroughput)**2
            totError += (throughput[1] - meanThroughput)**2
            totError += (throughput[2] - meanThroughput)**2
            print((throughput[0:3] - meanThroughput)**2)
            print("\n")
            
print("SSE: "+ str(totError))
Ieffect = I/8
Seffect = S/8
Meffect = M/8
Weffect = W/8
SMeffect = SM/8
SWeffect = SW/8
MWeffect = MW/8
SMWeffect = SMW/8
SSS = Seffect**2*24
SSM = Meffect**2*24
SSW = Weffect**2*24
SSSM = SMeffect**2*24
SSSW = SWeffect**2*24
SSMW = MWeffect**2*24
SSSMW = SMWeffect**2*24
SST = totError + SSS + SSM + SSW + SSSM + SSSW + SSMW + SSSMW
print(str(Ieffect)+" "+str(Seffect)+" "+str(Meffect)+" "+str(Weffect)+" "+str(SMeffect)+" "+str(SWeffect)+" "+str(MWeffect)+" "+str(SMWeffect))
print(str(SSS)+" "+str(SSM)+" "+str(SSW)+" "+str(SSSM)+" "+str(SSSW)+" "+str(SSMW)+" "+str(SSSMW))
print("SST: "+str(SST))
print(str(SSS*100/SST)+" "+str(SSM*100/SST)+" "+str(SSW*100/SST)+" "+str(SSSM*100/SST)+" "+str(SSSW*100/SST)+" "+str(SSMW*100/SST)+" "+str(SSSMW*100/SST))


Servers: 2	Middleware: 1	Worker Threads: 8

Throuhgput: 5165.0 5186.66 5101.73

Average Throughput: 5151.13

[  192.3769  1262.3809  2440.36  ]


Servers: 2	Middleware: 1	Worker Threads: 32

Throuhgput: 8637.29 8376.47 8309.3

Average Throughput: 8441.02

[ 38521.9129   4166.7025  17350.1584]


Servers: 2	Middleware: 2	Worker Threads: 8

Throuhgput: 10639.52 10901.28 10559.05

Average Throughput: 10699.95

[  3651.7849  40533.7689  19852.81  ]


Servers: 2	Middleware: 2	Worker Threads: 32

Throuhgput: 16851.91 17053.89 16422.41

Average Throughput: 16776.07

[   5751.7056   77183.9524  125075.3956]


Servers: 3	Middleware: 1	Worker Threads: 8

Throuhgput: 3697.74 3602.49 3701.07

Average Throughput: 3667.1

[  938.8096  4174.4521  1153.9609]


Servers: 3	Middleware: 1	Worker Threads: 32

Throuhgput: 7202.69 7054.47 7098.59

Average Throughput: 7118.58333333

[ 7073.93137834  4110.51951068   399.73337764]


Servers: 3	Middleware: 2	Worker Threads: 8

Throuhgput: 7130.41 7036.79 6874.92


In [3]:
totError = 0
S = 0
M = 0
W = 0
SM = 0
SW = 0
MW = 0
SMW = 0
I = 0
type = "50Set50Get"
for server in [2, 3]:
    for mw in [1,2]:
        for workers in [8, 32]:
            if server == 2:
                Svalue = -1
            else:
                Svalue = 1
            if mw == 1:
                Mvalue = -1
            else:
                Mvalue = 1
            if workers == 8:
                Wvalue = -1
            else:
                Wvalue = 1
            
            fileI = open("/home/andrea/Desktop/Final/Baseline6Prime/"+type+"_S"+str(server)+"_MW"+str(mw)+"_W"+str(workers)+"/results.txt", "r")
            linesI = []
            for line in fileI:
                linesI.append(line)

            xI = np.asarray(linesI)

            latency = np.zeros(4)
            latency[0] = float(xI[3].split(" ")[2])
            latency[1] = float(xI[3].split(" ")[3])
            latency[2] = float(xI[3].split(" ")[4])

            meanLatency = float(xI[4].split(" ")[3])
            I += meanLatency
            S += Svalue*meanLatency
            M += Mvalue*meanLatency
            W += Wvalue*meanLatency
            SM += Svalue*Mvalue*meanLatency
            SW += Svalue*Wvalue*meanLatency
            MW += Mvalue*Wvalue*meanLatency
            SMW += Svalue*Mvalue*Wvalue*meanLatency

            print(xI[0])
            print(xI[3])
            print(xI[4])
            totError += (latency[0] - meanLatency)**2
            totError += (latency[1] - meanLatency)**2
            totError += (latency[2] - meanLatency)**2
            print((latency[0:3] - meanLatency)**2)
            print("\n")
            
print("SSE: "+ str(totError))
Ieffect = I/8
Seffect = S/8
Meffect = M/8
Weffect = W/8
SMeffect = SM/8
SWeffect = SW/8
MWeffect = MW/8
SMWeffect = SMW/8
SSS = Seffect**2*24
SSM = Meffect**2*24
SSW = Weffect**2*24
SSSM = SMeffect**2*24
SSSW = SWeffect**2*24
SSMW = MWeffect**2*24
SSSMW = SMWeffect**2*24
SST = totError + SSS + SSM + SSW + SSSM + SSSW + SSMW + SSSMW
print(str(Ieffect)+" "+str(Seffect)+" "+str(Meffect)+" "+str(Weffect)+" "+str(SMeffect)+" "+str(SWeffect)+" "+str(MWeffect)+" "+str(SMWeffect))
print(str(SSS)+" "+str(SSM)+" "+str(SSW)+" "+str(SSSM)+" "+str(SSSW)+" "+str(SSMW)+" "+str(SSSMW))
print("SST: "+str(SST))
print(str(SSS*100/SST)+" "+str(SSM*100/SST)+" "+str(SSW*100/SST)+" "+str(SSSM*100/SST)+" "+str(SSSW*100/SST)+" "+str(SSMW*100/SST)+" "+str(SSSMW*100/SST))


Servers: 2	Middleware: 1	Worker Threads: 8

Response Time: 37.165 37.01 37.6261666667

Average Response Time: 37.2670555556
[ 0.01041534  0.06607756  0.12896079]


Servers: 2	Middleware: 1	Worker Threads: 32

Response Time: 22.2226666667 22.9155 22.9088333333

Average Response Time: 22.6823333333
[ 0.21129344  0.05436669  0.05130225]


Servers: 2	Middleware: 2	Worker Threads: 8

Response Time: 18.062 17.624 18.1933333333

Average Response Time: 17.9597777778
[ 0.01044938  0.11274672  0.0545482 ]


Servers: 2	Middleware: 2	Worker Threads: 32

Response Time: 11.396 11.266 11.7043333333

Average Response Time: 11.4554444444
[ 0.00353364  0.0358892   0.06194568]


Servers: 3	Middleware: 1	Worker Threads: 8

Response Time: 52.1331666667 53.2876666667 51.868

Average Response Time: 52.4296111111
[ 0.08787931  0.73625934  0.31540704]


Servers: 3	Middleware: 1	Worker Threads: 32

Response Time: 26.649 27.268 27.0398333333

Average Response Time: 26.9856111111
[ 0.11330704  0.07974348  0.00294